services:
  gulimall-product:
    build:
      context: ./gulimall-product
      dockerfile: ./gulimall-product/Dockerfile
#    volumes:
#      - $HOME/.m2/repository:/root/.m2/repository
    scale: 1
    ports:
      - 8082:8082
  gulimall-gateway:
    build:
      context: ./gulimall-gateway
      dockerfile: ./gulimall-gateway/Dockerfile
    scale: 1
    ports:
      - 8081:8081
  renren-fast:
    build:
      context: ./renren-fast
      dockerfile: ./renren-fast/Dockerfile
    scale: 1
    ports:
      - 8080:8080
  gulimall-coupon:
    build:
      context: ./gulimall-coupon
      dockerfile: ./gulimall-coupon/Dockerfile
    scale: 1
    ports:
      - 8083:8083
  gulimall-memberr:
    build:
      context: ./gulimall-member
      dockerfile: ./gulimall-member/Dockerfile
    scale: 1
    ports:
      - 8084:8084
#  gulimall-order:
#    build:
#      context: ./gulimall-order
#      dockerfile: ./gulimall-order/Dockerfile
#    scale: 1
#    ports:
#      - 8085:8085
#  gulimall-search:
#    build:
#      context: ./gulimall-search
#      dockerfile: ./gulimall-search/Dockerfile
#    scale: 1
#    ports:
#      - 8086:8086
#  gulimall-third-party:
#    build:
#      context: ./gulimall-third-party
#      dockerfile: ./gulimall-third-party/Dockerfile
#    scale: 1
#    ports:
#      - 8087:8087
#  gulimall-ware:
#    build:
#      context: ./gulimall-ware
#      dockerfile: ./gulimall-ware/Dockerfile
#    scale: 1
#    ports:
#      - 8088:8088
#
#  redis:
#    image: mysql
#    ports:
#      - 6379
#    volumes:
#      - mysql:/data
#
#volumes:
#  mysql:
