services:
  gulimall-product:
    build:
      context: ./gulimall-product
      dockerfile: ./gulimall-product/Dockerfile
    volumes:
      - $HOME/.m2/repository:/root/.m2/repository
    scale: 2
    ports:
      - 8082:8082
  gulimall-gateway:
    build:
      context: ./gulimall-gateway
      dockerfile: ./gulimall-gateway/Dockerfile
    volumes:
      - $HOME/.m2/repository:/root/.m2/repository
    scale: 2
    ports:
      - 8081:8081
  renren-fast:
    build:
      context: ./renren-fast
      dockerfile: ./renren-fast/Dockerfile
    volumes:
      - $HOME/.m2/repository:/root/.m2/repository
    scale: 2
    ports:
      - 8080:8080
#
#  redis:
#    image: mysql
#    ports:
#      - 6379
#    volumes:
#      - mysql:/data
#
#volumes:
#  mysql:
