services:
  gulimall:
    build: gulimall-gateway
    scale: 2
    ports:
      - 8080:8080

#  redis:
#    image: mysql
#    ports:
#      - 6379
#    volumes:
#      - mysql:/data
#
#volumes:
#  mysql:
