spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: nacos.allenjlchen
    thymeleaf:
      cache: false
    session:
      store-type: redis
  redis:
    host: 192.168.56.101
  ipAddr: 192.168.56.101
  server:
    port: 8086
